// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_aMLYXqDdkYSYXh2tE5-8upNUEr_3sbk',
    appId: '1:549203283084:android:8ee03e438df8f0a6eeffa9',
    messagingSenderId: '549203283084',
    projectId: 'drsocial-90e33',
    storageBucket: 'drsocial-90e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakUmmagFT7SMBWnaxlnMhevCZ27eBDkU',
    appId: '1:549203283084:ios:909162602e9c767aeeffa9',
    messagingSenderId: '549203283084',
    projectId: 'drsocial-90e33',
    storageBucket: 'drsocial-90e33.appspot.com',
    androidClientId: '549203283084-plr3cvdi163nd3skvldbnabmkkog676v.apps.googleusercontent.com',
    iosClientId: '549203283084-ca74njo2djpdtb4ajfs24he7idqflqnh.apps.googleusercontent.com',
    iosBundleId: 'com.drsocial.albaqer-new',
  );
}
